#!/bin/sh
# Resolve all dependencies that the application requires to run.

set -e

cd $(dirname $(dirname $0))

git submodule update --init

. script/lib/docker

docker-compose run --rm --no-deps backend yarn install --frozen-lockfile

docker-compose run --rm --no-deps frontend yarn install --frozen-lockfile
