#!/bin/sh
# Update application to run for its current checkout.

set -e

cd $(dirname $(dirname $0))

script/bootstrap

docker-compose up --detach postgres
docker-compose run --rm --no-deps backend wait-for-it postgres:5432 -- typeorm migration:run
